services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/html/
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}

volumes:
  caddy_data:
  caddy_config:
