services:
  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./:/var/www/html/
    restart: unless-stopped
    ports:
      - "8888:80"
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./:/var/www/html/
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
